version: '2.4'

services:
  server:
    ports:
      - '80:80'
    volumes:
      - ./api:/usr/src/app

  api:
    build:
      target: dev
    volumes:
      - ./api:/usr/src/app
    env_file: .env

  database:
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: ~
