app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
  path: /api/v1
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
