<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBlcEm6x\App_Symfony_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBlcEm6x/App_Symfony_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBlcEm6x.legacy');

    return;
}

if (!\class_exists(App_Symfony_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBlcEm6x\App_Symfony_KernelDevDebugContainer::class, App_Symfony_KernelDevDebugContainer::class, false);
}

return new \ContainerBlcEm6x\App_Symfony_KernelDevDebugContainer([
    'container.build_hash' => 'BlcEm6x',
    'container.build_id' => 'be721db4',
    'container.build_time' => 1613567651,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBlcEm6x');
