<?php

namespace ContainerBlcEm6x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBooksService extends App_Symfony_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Adapter\Repository\Books' shared autowired service.
     *
     * @return \App\Adapter\Repository\Books
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/Books.php';
        include_once \dirname(__DIR__, 4).'/src/Adapter/Repository/Books.php';

        return $container->privates['App\\Adapter\\Repository\\Books'] = new \App\Adapter\Repository\Books(($container->privates['.debug.book.client'] ?? $container->get_Debug_Book_ClientService()));
    }
}
