<?php

namespace ContainerBlcEm6x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateBasketHandlerService extends App_Symfony_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Domain\CommandHandler\CreateBasketHandler' shared autowired service.
     *
     * @return \App\Domain\CommandHandler\CreateBasketHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/CommandHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/CommandHandler/CreateBasketHandler.php';

        return $container->privates['App\\Domain\\CommandHandler\\CreateBasketHandler'] = new \App\Domain\CommandHandler\CreateBasketHandler(($container->privates['App\\Adapter\\Repository\\Baskets'] ?? $container->load('getBasketsService')), ($container->privates['App\\Adapter\\Repository\\Books'] ?? $container->load('getBooksService')));
    }
}
